apiVersion: v1
kind: DeploymentConfig
metadata:
  name: tomcat-ct
spec:
  template:
    metadata:
      labels:
        name: tomcat-ct
    spec:
      containers:
      - name: tomcat-ct
        image: 172.30.71.238:5000/sample01/tomcat:ct
        ports:
        - containerPort: 8080
          protocol: TCP
  replicas: 1
  selector:
    name: tomcat-ct
  triggers:
  - type: ImageChange
    imageChangeParams:
      automatic: true
      containerNames:
      - tomcat-ct
      from:
        kind: ImageStreamTag
        name: 172.30.71.238:5000/sample01/tomcat:ct
        ports:
  - type: ConfigChange
