apiVersion: v1
kind: DeploymentConfig
metadata:
  name: tomcat-sample
spec:
  template:
    metadata:
      labels:
        name: tomcat-sample
    spec:
      containers:
      - name: tomcat-latest
#        image: tomcat:latest
        image: 172.30.71.238:5000/sample01/tomcat:latest
        ports:
        - containerPort: 8080
          protocol: TCP
#        env:
#        - name: MYSQL_ROOT_PASSWORD
#          value: example
#        - name: MYSQL_DATABASE
#          value: redmine
  replicas: 1
  selector:
    name: tomcat-sample
  triggers:
  - type: ImageChange
    imageChangeParams:
      automatic: true
      containerNames:
      - tomcat-sample-latest
      from:
        kind: ImageStreamTag
#        name: tomcat:latest
        name: 172.30.71.238:5000/sample01/tomcat:latest
        ports:
  - type: ConfigChange
