apiVersion: v1
kind: BuildConfig
metadata:
  name: tomcat
spec:
  output:
    to:
      kind: ImageStreamTag
      name: tomcat:latest
  source:
    git:
      uri: https://github.com/yuji-k64613/openshift_tomcat.git
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: tomcat:8.0.43-jre8
    type: Docker
  triggers:
  - imageChange: {}
    type: ImageChange
