apiVersion: v1
kind: Service
metadata:
  name: tomcat-sample
spec:
  ports:
  - name: 8080-tcp
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 0
  selector:
    deploymentconfig: tomcat-sample
  type: NodePort
